import type { Metadata } from "next";
import "@/styles/global.css";

export const metadata: Metadata = {
  title: "Fade in out",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className="h-screen w-full flex justify-center bg-gray-950"
      >
        {children}
      </body>
    </html>
  );
}
